Update field names
cellannotation/cell-annotation-schema pull request #94
Opened 2024-01-22 09:20 UTC by mfutey

For [MVP-4961](https://capdevelopment.atlassian.net/browse/MVP-4961): 

1. Updated the following field names: 

    "cap_publication_authors_list" -> "authors_list"
    "cap_publication_timestamp" -> "publication_timestamp"
    "cap_publication_version" -> "publication_version"
    "cap_author_name" -> "main_author"
    "cap_author_orcid" -> "main_author_orcid"
    "cap_author_contact" -> "main_author_contact"

2. Changed the order of the fields so that the "cap_" fields are grouped together. The only .uns fields with "cap_" prefix are:

    "cap_publication_title"
    "cap_publication_description"
    "cap_publication_url"

2024-01-22 18:40 UTC, evanbiederstedt approved these changes
LGTM

2024-01-22 19:10 UTC, rm1113 requested changes
Please rename author related fields. We just need to remove `cap_` prefix

2024-01-22 19:11 UTC, evanbiederstedt commented
Apologies I missed the above; we had a slack discussion

I agree "main" could be a loaded term (whereby academics might think "most important"). 

Let's remove "main"

2024-01-23 08:01 UTC, mfutey commented
@rm1113 @evanbiederstedt I removed "main" from the author fields and changed "main_author" to "author_name"

2024-01-23 09:21 UTC, merged